### ISSUE TITLE
Nuxt and window is not defined error

### ISSUE THREAD

**Issue by lsbyerley** [MadimetjaShika/vuetify-google-autocomplete#30]
Looking to include this as a plugin in Nuxt and getting a `window is not defined` error. This is my plugin file

    import Vue from 'vue';
    import VuetifyGoogleAutocomplete from 'vuetify-google-autocomplete';
    
    Vue.use(VuetifyGoogleAutocomplete, {
      apiKey: 'the-key'
    });

 It appears the error is at `window.vgaMapState = {...}` and most likely `window.initVGAMaps = function(...)` in index.js

Should also note that the error doesn't come up during compile, but rather when loading the page the `vuetify-google-autocomplete` is used on

**Comment by NicolaeCasir** [comment]
I solved this problem with:

`...
plugins: [
    { src: '~/plugins/autocomplete.js', ssr: false},
    ...
]
...`

But anyway won't work. I do not have errors, but autocomplete don't work.

**Comment by MadimetjaShika** [comment]
Hi,

This error does make sense in the context of Nuxt. A simple fix is to first check if ``window`` and ``document`` are both defined in ``helper.js`` and ``index.js`` before trying to do anything. If they aren't defined (meaning we are in a server-side context, or something of the sort), the logic should simply return and not continue. If any of you are keen you're welcome to submit a PR and i'll merge it in. I'll publish the fix in the next release, which might be early next week. Alternatively I might only get a chance to check this out towards the end of the week.

PS: You could also check out #18 to see if that solution doesn't solve your problem in the interim.

**Comment by lsbyerley** [comment]
@MadimetjaShika played around with the solution you suggested, checking window and document, but that seems to lead to a `Cannot read property 'setAttribute' of null` in line 337 of VuetifyGoogleAutocomplete.js 

I also get errors using @NicolaeCasir suggestion.. so, I'll continue to debug.

**Comment by MadimetjaShika** [comment]
Hi @lsbyerley 

I have published a new release which should resolve this, ``2.0.0-Alpha.8``.

In order to get this working with nuxt, I had the following setup

#### nuxt.config.js
```javascript
module.exports = {
  //...
  build: {
    vendor: ['vuetify-google-autocomplete'],
    //...
  },
  plugins: ['~/plugins/vuetify', '~plugins/vuetify-google-autocomplete'],
  //...
}
```
or as suggested by @NicolaeCasir (both do work)
```javascript
module.exports = {
  //...
  plugins: ['~/plugins/vuetify', { src: '~/plugins/vuetify-google-autocomplete.js', ssr: false}],
  //...
}
```



#### plugins/vuetify-google-autocomplete.js
```javascript
import Vue from 'vue'
import vuetifyGoogleAutocomplete from 'vuetify-google-autocomplete'

Vue.use(vuetifyGoogleAutocomplete, {
  apiKey: '....',
})
```

#### .vue file
```
Everything else in this file remains standard.
```

Feel free to re-open this issue if you still face any problems.

**Comment by lsbyerley** [comment]
@MadimetjaShika Awesome, thank you for getting this to work. One issue I still encounter is a `navigator is not defined` error when loading the page directly in the url as opposed to navigating to it from index. I am setting `enable-geolocation="true"` in the component. If i set it to false, this doesn't happen

Secondly, and I can open another issue for this, is when setting the `types` prop to `(cities)`. In the example you have built, its passing an array, but the prop type is listed as string? I can't seem to get only cities to load at all.  

EDIT: was able to get cities working, I was passing in country as a string, not an array

**Comment by MadimetjaShika** [comment]
Hi @lsbyerley, please open a new issue for the ``navigator is not defined`` error. I will have a look into it in the meantime.

**Comment by lsbyerley** [comment]
#35 `navigator is not defined` issue created
